=== el-moudni-hicham/XML-LIBRARY-EXAMPLE/EX1/operator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xsd:element name="operator">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="client" type="TYPE_CLT" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    
    <xsd:complexType name="TYPE_CLT">
        <xsd:sequence>
            <xsd:element name="abonnement" type="TYPE_AB" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="code" type="xsd:ID"></xsd:attribute>
        <xsd:attribute name="nom" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="TYPE_AB">
        <xsd:sequence>
            <xsd:element name="facture" type="TYPE_FAC" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="num" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="type" default="TEL">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="TEL"></xsd:enumeration>
                    <xsd:enumeration value="FAX"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="dateAb" type="xsd:date"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="TYPE_FAC">
        <xsd:attribute name="numFact" type="xsd:string"></xsd:attribute>
        <xsd:attribute name="dateFact" type="xsd:date"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:float"></xsd:attribute>
        <xsd:attribute name="reglee" default="Non">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Oui"></xsd:enumeration>
                    <xsd:enumeration value="Non"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    
</xsd:schema>

=== el-moudni-hicham/XML-LIBRARY-EXAMPLE/EX1/operatorVerXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<operator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/MR%20SDIA/SDIA%202/TEC%20WEB/XML/TP%20XML%20Youssfi/EX1/operator.xsd">
    <client code="C1" nom="hicham">
        <abonnement num="A1" dateAb="2023-03-19">
            <facture numFact="F1" dateFact="2023-05-12" montant="900"/>
            <facture numFact="F2" dateFact="2023-05-12" montant="700"/>
        </abonnement>
        <abonnement num="A2" dateAb="2023-03-19">
            <facture numFact="F3" dateFact="2023-05-12" montant="900"/>
            <facture numFact="F4" dateFact="2023-05-12" montant="200"/>
            <facture numFact="F5" dateFact="2023-05-12" montant="100"/>
            <facture numFact="F6" dateFact="2023-05-12" montant="720"/>
        </abonnement>
    </client>
    <client code="C2" nom="ayoub">
        <abonnement num="A3" dateAb="2023-03-19">
            <facture numFact="F7" dateFact="2023-05-12" montant="1730"/>
        </abonnement>
    </client>
</operator>
